"""adicionando students e teachers ao modelo

Revision ID: bc65133d3714
Revises: 2df185641c25
Create Date: 2025-04-17 17:16:54.182596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc65133d3714'
down_revision = '2df185641c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategies', sa.PickleType(), nullable=False))
        batch_op.add_column(sa.Column('teachers', sa.PickleType(), nullable=False))
        batch_op.add_column(sa.Column('students', sa.PickleType(), nullable=False))
        batch_op.drop_column('strategy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('students')
        batch_op.drop_column('teachers')
        batch_op.drop_column('strategies')

    # ### end Alembic commands ###
