"""remover teachers e students do modelo

Revision ID: d072c951654e
Revises: 
Create Date: 2025-04-17 17:09:01.893778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd072c951654e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_column('students')
        batch_op.drop_column('teachers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teachers', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('students', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
