"""update messages

Revision ID: d8afa289f4d2
Revises: 60c310e1ee27
Create Date: 2025-04-26 16:28:55.415082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8afa289f4d2'
down_revision = '60c310e1ee27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messages', sa.PickleType(), nullable=False))
        batch_op.drop_column('content')
        batch_op.drop_column('username')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('content', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('messages')

    # ### end Alembic commands ###
